import { BRAND_LOGOS, type BrandLogoData } from "@/lib/config/brand-logos.generated";

/**
 * Brand logo resolution for targets.
 *
 * Known hosts resolve to their Simple Icons brand logo (offline data,
 * generated by scripts/generate-brand-logos.mjs); everything else — custom
 * targets and brands missing from the icon set — falls back to a letter
 * avatar colored from the dashboard palette.
 */

/** Silver for dark-on-dark logos (Apple/GitHub-style near-black hexes). */
export const LOGO_FALLBACK_COLOR = "#C0C0C0";

/**
 * Logos darker than this WCAG relative luminance are invisible on the void
 * background and render in silver instead. Telegram blue (~0.33) passes;
 * GitHub #181717 (~0.01) does not.
 */
export const DARK_LUMINANCE_THRESHOLD = 0.1;

/** WCAG relative luminance (0..1) of a 3/6-digit hex color. */
export function hexRelativeLuminance(hex: string): number {
  const full = hex.length === 3 ? hex.split("").map((c) => c + c).join("") : hex;
  const channel = (i: number): number => {
    const v = Number.parseInt(full.slice(i, i + 2), 16) / 255;
    return v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * channel(0) + 0.7152 * channel(2) + 0.0722 * channel(4);
}

/** Hostname of a URL, lowercased; falls back to the raw string on bad input. */
export function hostFromUrl(url: string): string {
  try {
    return new URL(url).hostname.toLowerCase();
  } catch {
    return url.toLowerCase();
  }
}

export type ResolvedBrandLogo =
  | { kind: "brand"; title: string; colorHex: string; path: string }
  | { kind: "avatar"; letter: string; seed: string };

/** Resolve a brand logo: known brand (with luminance guard) or letter avatar. */
export function resolveBrandLogo(host: string, name: string): ResolvedBrandLogo {
  const normalized = host.toLowerCase();
  const data: BrandLogoData | undefined = BRAND_LOGOS[normalized];
  if (data) {
    const dark = hexRelativeLuminance(data.hex) < DARK_LUMINANCE_THRESHOLD;
    return {
      kind: "brand",
      title: data.title,
      colorHex: dark ? LOGO_FALLBACK_COLOR : `#${data.hex}`,
      path: data.path,
    };
  }
  const letter = (name.trim()[0] ?? host.trim()[0] ?? "?").toUpperCase();
  return { kind: "avatar", letter, seed: normalized || name.toLowerCase() };
}

const AVATAR_PALETTE = [
  "bg-neon-dim text-neon",
  "bg-ok-dim text-ok",
  "bg-blocked-dim text-blocked",
  "bg-steel text-silver-bright",
] as const;

/** Deterministic dim palette class for a seed (stable across renders). */
export function avatarPaletteFor(seed: string): string {
  let hash = 0;
  for (let i = 0; i < seed.length; i += 1) hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  return AVATAR_PALETTE[hash % AVATAR_PALETTE.length] ?? AVATAR_PALETTE[0];
}
